ARG TRAEFIK_VERSION
FROM traefik:${TRAEFIK_VERSION} as traefik

FROM bearstech/debian:buster

ENV LANG=C.UTF-8
ENV HTTP_PROXY=""

RUN set -eux \
    &&  export http_proxy=${HTTP_PROXY} \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                python3 python3-pip \
    &&  python3 -m pip install "docker<=3.9" \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* /root/.cache \
    &&  update-alternatives --install /usr/bin/python python /usr/bin/python3 1

COPY --from=traefik /traefik /usr/local/bin/traefik

ARG TRAEFIK_VERSION
ARG TRAEFIK_MAJOR_VERSION
COPY ./traefik-${TRAEFIK_MAJOR_VERSION}.toml /etc/traefik/traefik.toml

COPY wait_for_services /usr/local/bin/wait_for_services
COPY traefik_hosts /usr/local/bin/traefik_hosts

ENTRYPOINT ["/usr/local/bin/traefik"]

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    io.containous.factory.version=${TRAEFIK_VERSION} \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-traefik \
    org.opencontainers.image.source=https://github.com/factorysh/docker-traefik/blob/${GIT_VERSION}/Dockerfile-${TRAEFIK_MAJOR_VERSION}
