version: "3"

services:
    traefik:
        image: bearstech/traefik-dev
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: "host"
        ports:
            - 8080
            - 80
