---

version: "3"

services:
    traefik:
        image: bearstech/traefik-dev:${TRAEFIK_VERSION}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            MYSQL_ROOT_PASSWORD: password
        expose:
            - 8080
            - 80

    mirror-mirror:
        image: bearstech/http-mirror
        hostname: mirror
        labels:
            traefik.enable: 'true'
            traefik.frontend.rule: Host:mirror
            traefik.http.routers.mirrorTraefik.rule: Host(`mirror`)
        expose:
            - 5000

    auth-mirror:
        image: bearstech/http-mirror
        hostname: auth-mirror
        labels:
            traefik.enable: 'true'
            # auth is bob / password
            traefik.frontend.rule: Host:auth
            traefik.frontend.auth.basic: >
                bob:$$apr1$$8cJXrdhG$$w69pUd0TFNhYAzo2Aut0A/
            traefik.http.routers.authMirrorTraefik.rule: Host(`auth`)
            traefik.http.routers.authMirrorTraefik.middlewares: auth
            traefik.http.middlewares.auth.basicauth.users: >
                bob:$$apr1$$8cJXrdhG$$w69pUd0TFNhYAzo2Aut0A/
        expose:
            - 5000

    empty-auth-mirror:
        image: bearstech/http-mirror
        hostname: empty-auth-mirror
        labels:
            traefik.enable: 'true'
            traefik.frontend.rule: Host:empty-auth
            traefik.frontend.auth.basic: ""
            traefik.http.routers.emptyAuthTraefik.rule: Host(`empty-auth`)
        expose:
            - 5000

    mysql:
        image: mariadb:10.1
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    goss:
        image: bearstech/debian:stretch
        volumes:
            - ../bin/current/goss:/usr/bin/goss
            - ../tests_traefik:/goss
            - ../hosts:/etc/hosts
        working_dir: /goss
        restart: 'no'
        depends_on:
            - traefik
            - mirror-mirror
            - auth-mirror
            - empty-auth-mirror
