---

version: "3"

services:
    traefik:
        image: bearstech/traefik-dev
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080
            - 80

    mirror:
        image: bearstech/http-mirror
        hostname: mirror
        labels:
            traefik.frontend.rule: Host:traefik
        ports:
            - 5000

    goss:
        image: bearstech/debian:stretch
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_traefik:/goss
        working_dir: /goss
        links:
            - traefik
