---

version: "3"

services:
    traefik:
        image: bearstech/traefik-dev:${TRAEFIK_VERSION}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 8080
            - 80

    mirror:
        image: bearstech/http-mirror
        hostname: mirror
        labels:
            traefik.frontend.rule: Host:traefik
            traefik.http.routers.traefik.rule: Host(`traefik`)
        ports:
            - 5000

    auth-mirror:
        image: bearstech/http-mirror
        hostname: auth-mirror
        labels:
            # auth is bob / password
            traefik.frontend.rule: Host:auth
            traefik.frontend.auth.basic: >
                bob:$$apr1$$8cJXrdhG$$w69pUd0TFNhYAzo2Aut0A/
            traefik.http.routers.router0.rule: Host(`auth`)
            traefik.http.routers.router0.middlewares: auth
            traefik.http.middlewares.auth.basicauth.users: >
                bob:$$apr1$$8cJXrdhG$$w69pUd0TFNhYAzo2Aut0A/
        ports:
            - 5000

    empty-auth-mirror:
        image: bearstech/http-mirror
        hostname: empty-auth-mirror
        labels:
            traefik.frontend.rule: Host:empty-auth
            traefik.frontend.auth.basic: ""
            traefik.http.routers.router1.rule: Host(`empty-auth`)
        ports:
            - 5000

    mysql:
        image: mariadb:10.1
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    goss:
        image: bearstech/debian:stretch
        volumes:
            - ../bin/current/goss:/usr/bin/goss
            - ../tests_traefik:/goss
        working_dir: /goss
        restart: 'no'
        links:
            - traefik
            - traefik:auth
            - traefik:empty-auth
