---

http:
    http://mirror/:
        status: 200
        no-follow-redirects: false
        timeout: 1000
        body:
            - '"Host":"mirror"'
            - '"hostname":"mirror"'

    http://auth/#oups:
        status: 401
        no-follow-redirects: false
        timeout: 1000

    http://auth/#ok:
        status: 200
        no-follow-redirects: false
        timeout: 1000
        username: bob
        password: password
        body:
            - '"Host":"auth"'
            - '"hostname":"auth-mirror"'

    http://empty-auth/:
        status: 200
        no-follow-redirects: false
        timeout: 1000

    http://traefik:8080/:
        status: 200
        no-follow-redirects: false
        timeout: 1000

    http://traefik:8080/api/http/services:
        status: 200
        no-follow-redirects: false
        timeout: 1000
        body:
            - 'auth-mirror-tests-traefik@docker'
