---

http:
    http://traefik/:
        status: 200
        no-follow-redirects: false
        timeout: 1000
        body:
            - '"Host":"traefik"'
            - '"hostname":"mirror"'

    http://auth/#oups:
        status: 401
        no-follow-redirects: false
        timeout: 1000

    http://auth/#ok:
        status: 200
        no-follow-redirects: false
        timeout: 1000
        username: bob
        password: password
        body:
            - '"Host":"auth"'
            - '"hostname":"auth-mirror"'

    http://empty-auth/:
        status: 200
        no-follow-redirects: false
        timeout: 1000
